"use client";

import { FileDownIcon, LoaderCircleIcon } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { downloadCsv } from "@/components/export/csv";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { getUserMessage } from "@/lib/api/errors";
import { endOfZonedDay, startOfZonedDay } from "@/lib/date";

import { fetchUserStatementCsv } from "./api";

/** Downloads the API-generated account statement (CSV) for all time or a date range. */
export function StatementDialog({ userId, name }: { userId: string; name: string }) {
  const [open, setOpen] = useState(false);
  const [allTime, setAllTime] = useState(true);
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [busy, setBusy] = useState(false);
  const invalid = !allTime && (!from || !to || from > to);

  async function download() {
    setBusy(true);
    try {
      const csv = await fetchUserStatementCsv(
        userId,
        allTime
          ? { allTime: true }
          : { from: startOfZonedDay(from).toISOString(), to: endOfZonedDay(to).toISOString() },
      );
      const safeName = name.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "customer";
      downloadCsv(
        csv.replace(/^﻿/, ""),
        `statement-${safeName}-${allTime ? "all-time" : `${from}-to-${to}`}.csv`,
      );
      toast.success("Statement downloaded");
      setOpen(false);
    } catch (error) {
      toast.error(getUserMessage(error));
    } finally {
      setBusy(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm">
          <FileDownIcon aria-hidden />
          Statement
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>Download statement</DialogTitle>
          <DialogDescription>
            A financial statement for {name}, generated by the API as a CSV file. It contains
            personal data.
          </DialogDescription>
        </DialogHeader>
        <fieldset className="grid gap-2 text-sm">
          <legend className="sr-only">Period</legend>
          <label className="flex items-center gap-2">
            <input
              type="radio"
              name="statement-period"
              checked={allTime}
              onChange={() => {
                setAllTime(true);
              }}
            />
            All time
          </label>
          <label className="flex items-center gap-2">
            <input
              type="radio"
              name="statement-period"
              checked={!allTime}
              onChange={() => {
                setAllTime(false);
              }}
            />
            Date range (WAT)
          </label>
        </fieldset>
        {!allTime && (
          <div className="grid grid-cols-2 gap-2">
            <div className="grid gap-1">
              <Label htmlFor="statement-from">From</Label>
              <Input
                id="statement-from"
                type="date"
                value={from}
                max={to || undefined}
                onChange={(e) => {
                  setFrom(e.target.value);
                }}
              />
            </div>
            <div className="grid gap-1">
              <Label htmlFor="statement-to">To</Label>
              <Input
                id="statement-to"
                type="date"
                value={to}
                min={from || undefined}
                onChange={(e) => {
                  setTo(e.target.value);
                }}
              />
            </div>
          </div>
        )}
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => {
              setOpen(false);
            }}
          >
            Cancel
          </Button>
          <Button onClick={() => void download()} disabled={busy || invalid}>
            {busy && <LoaderCircleIcon className="animate-spin" aria-hidden />}
            Download CSV
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
